// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxvvsldejombnmddsiim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54dnZzbGRlam9tYm5tZGRzaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTIxNTEsImV4cCI6MjA1ODY2ODE1MX0.IQyGAnWobLZTa8_i6M2sQR5gxO0tDut6u-dpgaq7EGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);